# Generated by Django 5.0.1 on 2024-03-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='jatin', max_length=100),
            preserve_default=False,
        ),
    ]
